[package]
name = "example"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]

[dev-dependencies]
crate-compile-test = { path = ".." }

[[test]]
name = "run_compile_tests"
harness = false
